services:
  - type: web
    name: sportify
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn sportify.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
