# Generated by Django 6.1.1 on 2026-09-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL for demonstration', max_length=500)),
                ('icon', models.CharField(default='bi-trophy', help_text='Bootstrap icon class name, e.g. bi-dribbble', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Standard retail price', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Promotional discounted price if applicable', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=20, help_text='Number of units in stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL for demonstration', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=25)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to display on the homepage featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide product from the store')),
                ('sizes', models.CharField(blank=True, default='Standard', help_text='Comma-separated variants/sizes e.g. S, M, L, XL or Standard', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
